Mobile App
ShaddyMore/My_portfolio1 pull request #1
Opened 2022-09-27 12:43 UTC by ShaddyMore

# My second Pull Request. I did the following:
-use HTML/CSS best practices
-Add HTML file
-Add CSS file 
-Add linters files

2022-09-27 13:09 UTC, mckent05 reviewed
Hi @ShaddyMore , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

You have submitted a project, that doesn't have linters set up. Please up linters, as they help to ensure you write clean and maintainable code

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-28 11:39 UTC, bobb-Rob requested changes
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have linters set up. Please up linters, as they help to ensure you write clean and maintainable code

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-30 02:09 UTC, emmiiorji requested changes
Hi @ShaddyMore, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Almost there](https://user-images.githubusercontent.com/20554583/193174667-26d5737d-a449-4454-ab25-2d24ca43e12b.gif)


## Good Highlights✔

- Linters are set up and checks are passing
- PR is descriptive
- Good commit messages


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 02:09 UTC, emmiiorji commented on index.html
> +        <img class="union"  src="/images/Union.png" alt="">
Kindly ensure that the hamburger button (in a `nav` tag) at the top right of the page is shown in your chosen template design.

Also, note that typically the `header` tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.

Your design:
![image](https://user-images.githubusercontent.com/20554583/193172022-e04fdf44-8a03-42a8-bd06-0cc32ed2b612.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/193171662-414def13-243f-4a1c-8db2-98ec82e83ced.png)

2022-09-30 02:09 UTC, emmiiorji commented on index.html
> +           through some of my work and<br>experience! If you like what you see and<br>have a project
Kindly use a section tag for the headline section. This section isn't the footer of the page as the footer will be implemented in a future milestone.

2022-09-30 02:09 UTC, emmiiorji commented on styles.css
> +}
I can see that you try to give different elements on the page `position: absolute` properties while trying to manually adjust their top positions by assigning large padding.

I recommend that you allow the flow of the elements on the page and use absolute positions only when necessary. This will make positioning other elements easier.

2022-09-30 02:09 UTC, emmiiorji commented on index.html
> +
Kindly include the social icons below the `Let's Connect` button in order to match your chosen design template.

Your design:
![image](https://user-images.githubusercontent.com/20554583/193174517-bef32ab5-19fa-43d7-b1a5-f02b4ab98df8.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/193174490-18756577-c9a4-4649-832a-aef8a001fe67.png)

2022-09-30 02:22 UTC, emmiiorji commented on index.html
> +      <h2><p>I'm Shadrach<br>Glad to see<br>you!</p><br><h2>
I recommend that you make this main title ("I'm Shedrach ...") to be a `h1` tag. If you want that google (and other search engines) know about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info. The main title (e.g., "I'm Marianne ...") is an h1 tag.

2022-09-30 02:24 UTC, emmiiorji commented on index.html
> +      <h2><p>I'm Shadrach<br>Glad to see<br>you!</p><br><h2>
- Kindly include the background image (as a CSS background) to match your chosen design template
  Your design:
   ![image](https://user-images.githubusercontent.com/20554583/193175680-cae9e99f-f2b6-4b28-b18b-da5a6532e128.png)

   Figma Design:
    ![image](https://user-images.githubusercontent.com/20554583/193175714-68d87c54-79b9-42ca-ae39-40a427773b7f.png)

2022-09-30 14:32 UTC, jerryowusu approved these changes
Hi @ShaddyMore :wave: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![wow approved](https://user-images.githubusercontent.com/65233860/193292273-79693baa-5423-4071-a507-bcd9354cc493.gif)


## Highlights
:heavy_check_mark: Linters are set up and checks are passing
:heavy_check_mark: PR is descriptive
:heavy_check_mark: Good commit messages

## Optional suggestions

- [ ] Kindly give your branch names more meaningful names that describes what it does eg: `mobile-version`, `desktop-setup` etc instead of `feature-1` or `feature-a`. This will make your code look more proffessional and easy to navigate. 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 14:32 UTC, jerryowusu commented on index.html
> +      </h1>
[OPTIONAL] Kindly adding width to the h1 since it is pushing the text to the right thereby creating an empty white space. 

![Screenshot from 2022-09-30 14-23-23](https://user-images.githubusercontent.com/65233860/193291903-073939d4-23de-4084-9dd4-4efb6923c595.png)

2022-09-30 17:47 UTC, merged